[package]
name = "crossflow-native-api-examples"
version = "0.0.4"
edition = "2021"

[[bin]]
name = "delivery-instructions"
path = "src/delivery_instructions.rs"

[[bin]]
name = "make-a-request"
path = "src/make_a_request.rs"

[dependencies]
crossflow = { path = "../../" }
async-std = "1.12"
