name: ci_linux

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # The final 1 indicates that we want to run this test on Tuesdays, making
    # this a weekly test.
    - cron:  '30 2 * * 1'
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        rust-version: [stable]

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Get apt dependencies
      run: sudo apt-get install protobuf-compiler

    - name: Setup rust
      run: rustup default ${{ matrix.rust-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Setup nodejs
      run: pnpm env use --global lts

    - name: Test default features
      run: |
        cargo test --workspace

    - name: Test single_threaded_async
      run: |
        rm -rf target/debug/build
        cargo test --features single_threaded_async

    - name: Test diagram
      run: |
        rm -rf target/debug/build
        cargo test --workspace -F=diagram

    - name: Test trace
      run: |
        rm -rf target/debug/build
        cargo test --workspace -F=trace

    - name: Test all capabilities combined
      run: |
        rm -rf target/
        cargo test --workspace -F=maximal

    - name: Build docs
      run: cargo doc --no-deps --all-features

